### ISSUE TITLE
A bug at the model order

### ISSUE THREAD

**Issue by qianchd** [ypan1988/jmcm#1]
Hi Pan, Thanks for your amazing work. When applying your package, I find the something goes wrong when I set the model order in the parameter "triple " to be zero. After check, I find that

In line 206-207, the code file "jmcm.R", the loop could not accept parameter 0.

I hope this will be something helpful for fixing the issues.

**Comment by ypan1988** [comment]
bug fixed in the coming jmcm 0.2.3
